[tox]
envlist = py311,py312,py313,sdist

[gh]
python =
    3.13 = py313, sdist
    3.12 = py312
    3.11 = py311

[testenv]
package = wheel
deps =
    pytest
    pexpect
    # Until hypno's run_in_thread is released
    {toxinidir}/third_party/hypno
commands = pytest tests {posargs}

[testenv:sdist]
package = sdist
